@startuml


Користувач -> OpenWeatherMap + : Запит
Користувач <-- OpenWeatherMap : Відповідь

OpenWeatherMap --> ОбробникВідповіді --++ : Відповідь
activate ОбробникВідповіді
ОбробникВідповіді -> БазаДаних --++ : Збереження погодних даних


activate БазаДаних
Користувач -> БазаДаних: Запит
Користувач <-- БазаДаних: Відповідь



@enduml